const colors = require("tailwindcss/colors");

module.exports = {
  darkMode: "media",
  plugins: [],
  presets: [],
  purge: ["./src/**/*.{tsx,mdx}"],
  theme: {
    animation: {
      bounce: "bounce 1s infinite",
      none: "none",
      ping: "ping 1s cubic-bezier(0, 0, 0.2, 1) infinite",
      pulse: "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      spin: "spin 1s linear infinite",
    },
    backgroundColor: (theme) => theme("colors"),
    backgroundImage: {
      "gradient-to-b": "linear-gradient(to bottom, var(--tw-gradient-stops))",
      "gradient-to-bl":
        "linear-gradient(to bottom left, var(--tw-gradient-stops))",
      "gradient-to-br":
        "linear-gradient(to bottom right, var(--tw-gradient-stops))",
      "gradient-to-l": "linear-gradient(to left, var(--tw-gradient-stops))",
      "gradient-to-r": "linear-gradient(to right, var(--tw-gradient-stops))",
      "gradient-to-t": "linear-gradient(to top, var(--tw-gradient-stops))",
      "gradient-to-tl":
        "linear-gradient(to top left, var(--tw-gradient-stops))",
      "gradient-to-tr":
        "linear-gradient(to top right, var(--tw-gradient-stops))",
      none: "none",
    },
    backgroundOpacity: (theme) => theme("opacity"),
    backgroundPosition: {
      bottom: "bottom",
      center: "center",
      left: "left",
      "left-bottom": "left bottom",
      "left-top": "left top",
      right: "right",
      "right-bottom": "right bottom",
      "right-top": "right top",
      top: "top",
    },
    backgroundSize: {
      auto: "auto",
      contain: "contain",
      cover: "cover",
    },
    borderColor: (theme) => ({
      ...theme("colors"),
      DEFAULT: theme("colors.gray.200", "currentColor"),
    }),
    borderOpacity: (theme) => theme("opacity"),
    borderRadius: {
      "2xl": "1rem",
      "3xl": "1.5rem",
      DEFAULT: "0.25rem",
      full: "9999px",
      lg: "0.5rem",
      md: "0.375rem",
      none: "0px",
      sm: "0.125rem",
      xl: "0.75rem",
    },
    borderWidth: {
      0: "0px",
      2: "2px",
      4: "4px",
      8: "8px",
      DEFAULT: "1px",
    },
    boxShadow: {
      "2xl": "0 25px 50px -12px rgba(0, 0, 0, 0.25)",
      DEFAULT:
        "0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)",
      inner: "inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)",
      lg:
        "0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)",
      md:
        "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)",
      none: "none",
      sm: "0 1px 2px 0 rgba(0, 0, 0, 0.05)",
      xl:
        "0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)",
    },
    colors: {
      black: colors.black,
      blue: colors.blue,
      coolgray: colors.coolGray,
      current: "currentColor",
      gray: colors.warmGray,
      green: colors.emerald,
      indigo: colors.indigo,
      pink: colors.pink,
      purple: colors.violet,
      red: colors.red,
      transparent: "transparent",
      white: colors.white,
      yellow: colors.amber,
    },
    container: {},
    cursor: {
      auto: "auto",
      default: "default",
      move: "move",
      "not-allowed": "not-allowed",
      pointer: "pointer",
      text: "text",
      wait: "wait",
    },
    divideColor: (theme) => theme("borderColor"),
    divideOpacity: (theme) => theme("borderOpacity"),
    divideWidth: (theme) => theme("borderWidth"),
    fill: { current: "currentColor" },
    flex: {
      1: "1 1 0%",
      auto: "1 1 auto",
      initial: "0 1 auto",
      none: "none",
    },
    flexGrow: {
      0: "0",
      DEFAULT: "1",
    },
    flexShrink: {
      0: "0",
      DEFAULT: "1",
    },
    fontFamily: {
      mono: [
        "ui-monospace",
        "SFMono-Regular",
        "Menlo",
        "Monaco",
        "Consolas",
        '"Liberation Mono"',
        '"Courier New"',
        "monospace",
      ],
      sans: [
        "ui-sans-serif",
        "system-ui",
        "-apple-system",
        "BlinkMacSystemFont",
        '"Segoe UI"',
        "Roboto",
        '"Helvetica Neue"',
        "Arial",
        '"Noto Sans"',
        "sans-serif",
        '"Apple Color Emoji"',
        '"Segoe UI Emoji"',
        '"Segoe UI Symbol"',
        '"Noto Color Emoji"',
      ],
      serif: [
        "ui-serif",
        "Georgia",
        "Cambria",
        '"Times New Roman"',
        "Times",
        "serif",
      ],
    },
    fontSize: {
      "2xl": ["1.5rem", { lineHeight: "2rem" }],
      "3xl": ["1.875rem", { lineHeight: "2.25rem" }],
      "4xl": ["2.25rem", { lineHeight: "2.5rem" }],
      "5xl": ["3rem", { lineHeight: "1" }],
      "6xl": ["3.75rem", { lineHeight: "1" }],
      "7xl": ["4.5rem", { lineHeight: "1" }],
      "8xl": ["6rem", { lineHeight: "1" }],
      "9xl": ["8rem", { lineHeight: "1" }],
      base: ["1rem", { lineHeight: "1.5rem" }],
      lg: ["1.125rem", { lineHeight: "1.75rem" }],
      sm: ["0.875rem", { lineHeight: "1.25rem" }],
      xl: ["1.25rem", { lineHeight: "1.75rem" }],
      xs: ["0.75rem", { lineHeight: "1rem" }],
    },
    fontWeight: {
      black: "900",
      bold: "700",
      extrabold: "800",
      extralight: "200",
      light: "300",
      medium: "500",
      normal: "400",
      semibold: "600",
      thin: "100",
    },
    gap: (theme) => theme("spacing"),
    gradientColorStops: (theme) => theme("colors"),
    gridAutoColumns: {
      auto: "auto",
      fr: "minmax(0, 1fr)",
      max: "max-content",
      min: "min-content",
    },
    gridAutoRows: {
      auto: "auto",
      fr: "minmax(0, 1fr)",
      max: "max-content",
      min: "min-content",
    },
    gridColumn: {
      auto: "auto",
      "span-1": "span 1 / span 1",
      "span-10": "span 10 / span 10",
      "span-11": "span 11 / span 11",
      "span-12": "span 12 / span 12",
      "span-2": "span 2 / span 2",
      "span-3": "span 3 / span 3",
      "span-4": "span 4 / span 4",
      "span-5": "span 5 / span 5",
      "span-6": "span 6 / span 6",
      "span-7": "span 7 / span 7",
      "span-8": "span 8 / span 8",
      "span-9": "span 9 / span 9",
      "span-full": "1 / -1",
    },
    gridColumnEnd: {
      1: "1",
      10: "10",
      11: "11",
      12: "12",
      13: "13",
      2: "2",
      3: "3",
      4: "4",
      5: "5",
      6: "6",
      7: "7",
      8: "8",
      9: "9",
      auto: "auto",
    },
    gridColumnStart: {
      1: "1",
      10: "10",
      11: "11",
      12: "12",
      13: "13",
      2: "2",
      3: "3",
      4: "4",
      5: "5",
      6: "6",
      7: "7",
      8: "8",
      9: "9",
      auto: "auto",
    },
    gridRow: {
      auto: "auto",
      "span-1": "span 1 / span 1",
      "span-2": "span 2 / span 2",
      "span-3": "span 3 / span 3",
      "span-4": "span 4 / span 4",
      "span-5": "span 5 / span 5",
      "span-6": "span 6 / span 6",
      "span-full": "1 / -1",
    },
    gridRowEnd: {
      1: "1",
      2: "2",
      3: "3",
      4: "4",
      5: "5",
      6: "6",
      7: "7",
      auto: "auto",
    },
    gridRowStart: {
      1: "1",
      2: "2",
      3: "3",
      4: "4",
      5: "5",
      6: "6",
      7: "7",
      auto: "auto",
    },
    gridTemplateColumns: {
      1: "repeat(1, minmax(0, 1fr))",
      10: "repeat(10, minmax(0, 1fr))",
      11: "repeat(11, minmax(0, 1fr))",
      12: "repeat(12, minmax(0, 1fr))",
      2: "repeat(2, minmax(0, 1fr))",
      3: "repeat(3, minmax(0, 1fr))",
      4: "repeat(4, minmax(0, 1fr))",
      5: "repeat(5, minmax(0, 1fr))",
      6: "repeat(6, minmax(0, 1fr))",
      7: "repeat(7, minmax(0, 1fr))",
      8: "repeat(8, minmax(0, 1fr))",
      9: "repeat(9, minmax(0, 1fr))",
      none: "none",
    },
    gridTemplateRows: {
      1: "repeat(1, minmax(0, 1fr))",
      2: "repeat(2, minmax(0, 1fr))",
      3: "repeat(3, minmax(0, 1fr))",
      4: "repeat(4, minmax(0, 1fr))",
      5: "repeat(5, minmax(0, 1fr))",
      6: "repeat(6, minmax(0, 1fr))",
      none: "none",
    },
    height: (theme) => ({
      auto: "auto",
      ...theme("spacing"),
      "1/2": "50%",
      "1/3": "33.333333%",
      "1/4": "25%",
      "1/5": "20%",
      "1/6": "16.666667%",
      "2/3": "66.666667%",
      "2/4": "50%",
      "2/5": "40%",
      "2/6": "33.333333%",
      "3/4": "75%",
      "3/5": "60%",
      "3/6": "50%",
      "4/5": "80%",
      "4/6": "66.666667%",
      "5/6": "83.333333%",
      full: "100%",
      screen: "100vh",
    }),
    inset: (theme, { negative }) => ({
      auto: "auto",
      ...theme("spacing"),
      ...negative(theme("spacing")),
      "-1/2": "-50%",
      "-1/3": "-33.333333%",
      "-1/4": "-25%",
      "-2/3": "-66.666667%",
      "-2/4": "-50%",
      "-3/4": "-75%",
      "-full": "-100%",
      "1/2": "50%",
      "1/3": "33.333333%",
      "1/4": "25%",
      "2/3": "66.666667%",
      "2/4": "50%",
      "3/4": "75%",
      full: "100%",
    }),
    keyframes: {
      bounce: {
        "0%, 100%": {
          animationTimingFunction: "cubic-bezier(0.8,0,1,1)",
          transform: "translateY(-25%)",
        },
        "50%": {
          animationTimingFunction: "cubic-bezier(0,0,0.2,1)",
          transform: "none",
        },
      },
      ping: {
        "75%, 100%": {
          opacity: "0",
          transform: "scale(2)",
        },
      },
      pulse: {
        "50%": {
          opacity: ".5",
        },
      },
      spin: {
        to: {
          transform: "rotate(360deg)",
        },
      },
    },
    letterSpacing: {
      normal: "0em",
      tight: "-0.025em",
      tighter: "-0.05em",
      wide: "0.025em",
      wider: "0.05em",
      widest: "0.1em",
    },
    lineHeight: {
      10: "2.5rem",
      3: ".75rem",
      4: "1rem",
      5: "1.25rem",
      6: "1.5rem",
      7: "1.75rem",
      8: "2rem",
      9: "2.25rem",
      loose: "2",
      none: "1",
      normal: "1.5",
      relaxed: "1.625",
      snug: "1.375",
      tight: "1.25",
    },
    listStyleType: {
      decimal: "decimal",
      disc: "disc",
      none: "none",
    },
    margin: (theme, { negative }) => ({
      auto: "auto",
      ...theme("spacing"),
      ...negative(theme("spacing")),
    }),
    maxHeight: (theme) => ({
      ...theme("spacing"),
      full: "100%",
      screen: "100vh",
    }),
    maxWidth: (theme, { breakpoints }) => ({
      0: "0rem",
      "2xl": "42rem",
      "3xl": "48rem",
      "4xl": "56rem",
      "5xl": "64rem",
      "6xl": "72rem",
      "7xl": "80rem",
      full: "100%",
      lg: "32rem",
      max: "max-content",
      md: "28rem",
      min: "min-content",
      none: "none",
      prose: "65ch",
      sm: "24rem",
      xl: "36rem",
      xs: "20rem",
      ...breakpoints(theme("screens")),
    }),
    minHeight: {
      0: "0px",
      full: "100%",
      screen: "100vh",
    },
    minWidth: {
      0: "0px",
      full: "100%",
      max: "max-content",
      min: "min-content",
    },
    objectPosition: {
      bottom: "bottom",
      center: "center",
      left: "left",
      "left-bottom": "left bottom",
      "left-top": "left top",
      right: "right",
      "right-bottom": "right bottom",
      "right-top": "right top",
      top: "top",
    },
    opacity: {
      0: "0",
      10: "0.1",
      100: "1",
      20: "0.2",
      25: "0.25",
      30: "0.3",
      40: "0.4",
      5: "0.05",
      50: "0.5",
      60: "0.6",
      70: "0.7",
      75: "0.75",
      80: "0.8",
      90: "0.9",
      95: "0.95",
    },
    order: {
      1: "1",
      10: "10",
      11: "11",
      12: "12",
      2: "2",
      3: "3",
      4: "4",
      5: "5",
      6: "6",
      7: "7",
      8: "8",
      9: "9",
      first: "-9999",
      last: "9999",
      none: "0",
    },
    outline: {
      black: ["2px dotted black", "2px"],
      none: ["2px solid transparent", "2px"],
      white: ["2px dotted white", "2px"],
    },
    padding: (theme) => theme("spacing"),
    placeholderColor: (theme) => theme("colors"),
    placeholderOpacity: (theme) => theme("opacity"),
    ringColor: (theme) => ({
      DEFAULT: theme("colors.blue.500", "#3b82f6"),
      ...theme("colors"),
    }),
    ringOffsetColor: (theme) => theme("colors"),
    ringOffsetWidth: {
      0: "0px",
      1: "1px",
      2: "2px",
      4: "4px",
      8: "8px",
    },
    ringOpacity: (theme) => ({
      DEFAULT: "0.5",
      ...theme("opacity"),
    }),
    ringWidth: {
      0: "0px",
      1: "1px",
      2: "2px",
      4: "4px",
      8: "8px",
      DEFAULT: "3px",
    },
    rotate: {
      "-1": "-1deg",
      "-12": "-12deg",
      "-180": "-180deg",
      "-2": "-2deg",
      "-3": "-3deg",
      "-45": "-45deg",
      "-6": "-6deg",
      "-90": "-90deg",
      0: "0deg",
      1: "1deg",
      12: "12deg",
      180: "180deg",
      2: "2deg",
      3: "3deg",
      45: "45deg",
      6: "6deg",
      90: "90deg",
    },
    scale: {
      0: "0",
      100: "1",
      105: "1.05",
      110: "1.1",
      125: "1.25",
      150: "1.5",
      50: ".5",
      75: ".75",
      90: ".9",
      95: ".95",
    },
    screens: {
      "2xl": "1536px",
      lg: "1024px",
      md: "768px",
      sm: "640px",
      xl: "1280px",
    },
    skew: {
      "-1": "-1deg",
      "-12": "-12deg",
      "-2": "-2deg",
      "-3": "-3deg",
      "-6": "-6deg",
      0: "0deg",
      1: "1deg",
      12: "12deg",
      2: "2deg",
      3: "3deg",
      6: "6deg",
    },
    space: (theme, { negative }) => ({
      ...theme("spacing"),
      ...negative(theme("spacing")),
    }),
    spacing: {
      0: "0px",
      0.5: "0.125rem",
      1: "0.25rem",
      1.5: "0.375rem",
      10: "2.5rem",
      11: "2.75rem",
      12: "3rem",
      14: "3.5rem",
      16: "4rem",
      2: "0.5rem",
      2.5: "0.625rem",
      20: "5rem",
      24: "6rem",
      28: "7rem",
      3: "0.75rem",
      3.5: "0.875rem",
      32: "8rem",
      36: "9rem",
      4: "1rem",
      40: "10rem",
      44: "11rem",
      48: "12rem",
      5: "1.25rem",
      52: "13rem",
      56: "14rem",
      6: "1.5rem",
      60: "15rem",
      64: "16rem",
      7: "1.75rem",
      72: "18rem",
      8: "2rem",
      80: "20rem",
      9: "2.25rem",
      96: "24rem",
      px: "1px",
    },
    stroke: {
      current: "currentColor",
    },
    strokeWidth: {
      0: "0",
      1: "1",
      2: "2",
    },
    textColor: (theme) => theme("colors"),
    textOpacity: (theme) => theme("opacity"),
    transformOrigin: {
      bottom: "bottom",
      "bottom-left": "bottom left",
      "bottom-right": "bottom right",
      center: "center",
      left: "left",
      right: "right",
      top: "top",
      "top-left": "top left",
      "top-right": "top right",
    },
    transitionDelay: {
      100: "100ms",
      1000: "1000ms",
      150: "150ms",
      200: "200ms",
      300: "300ms",
      500: "500ms",
      700: "700ms",
      75: "75ms",
    },
    transitionDuration: {
      100: "100ms",
      1000: "1000ms",
      150: "150ms",
      200: "200ms",
      300: "300ms",
      500: "500ms",
      700: "700ms",
      75: "75ms",
      DEFAULT: "150ms",
    },
    transitionProperty: {
      DEFAULT:
        "background-color, border-color, color, fill, stroke, opacity, box-shadow, transform",
      all: "all",
      colors: "background-color, border-color, color, fill, stroke",
      none: "none",
      opacity: "opacity",
      shadow: "box-shadow",
      transform: "transform",
    },
    transitionTimingFunction: {
      DEFAULT: "cubic-bezier(0.4, 0, 0.2, 1)",
      in: "cubic-bezier(0.4, 0, 1, 1)",
      "in-out": "cubic-bezier(0.4, 0, 0.2, 1)",
      linear: "linear",
      out: "cubic-bezier(0, 0, 0.2, 1)",
    },
    translate: (theme, { negative }) => ({
      ...theme("spacing"),
      ...negative(theme("spacing")),
      "-1/2": "-50%",
      "-1/3": "-33.333333%",
      "-1/4": "-25%",
      "-2/3": "-66.666667%",
      "-2/4": "-50%",
      "-3/4": "-75%",
      "-full": "-100%",
      "1/2": "50%",
      "1/3": "33.333333%",
      "1/4": "25%",
      "2/3": "66.666667%",
      "2/4": "50%",
      "3/4": "75%",
      full: "100%",
    }),
    width: (theme) => ({
      auto: "auto",
      ...theme("spacing"),
      "1/12": "8.333333%",
      "1/2": "50%",
      "1/3": "33.333333%",
      "1/4": "25%",
      "1/5": "20%",
      "1/6": "16.666667%",
      "10/12": "83.333333%",
      "11/12": "91.666667%",
      "2/12": "16.666667%",
      "2/3": "66.666667%",
      "2/4": "50%",
      "2/5": "40%",
      "2/6": "33.333333%",
      "3/12": "25%",
      "3/4": "75%",
      "3/5": "60%",
      "3/6": "50%",
      "4/12": "33.333333%",
      "4/5": "80%",
      "4/6": "66.666667%",
      "5/12": "41.666667%",
      "5/6": "83.333333%",
      "6/12": "50%",
      "7/12": "58.333333%",
      "8/12": "66.666667%",
      "9/12": "75%",
      full: "100%",
      max: "max-content",
      min: "min-content",
      screen: "100vw",
    }),
    zIndex: {
      0: "0",
      10: "10",
      20: "20",
      30: "30",
      40: "40",
      50: "50",
      auto: "auto",
    },
  },
  variantOrder: [
    "first",
    "last",
    "odd",
    "even",
    "visited",
    "checked",
    "group-hover",
    "group-focus",
    "focus-within",
    "hover",
    "focus",
    "focus-visible",
    "active",
    "disabled",
  ],
  variants: {
    accessibility: ["responsive", "focus-within", "focus"],
    alignContent: ["responsive"],
    alignItems: ["responsive"],
    alignSelf: ["responsive"],
    animation: ["responsive"],
    appearance: ["responsive"],
    backgroundAttachment: ["responsive"],
    backgroundClip: ["responsive"],
    backgroundColor: [
      "responsive",
      "dark",
      "group-hover",
      "focus-within",
      "hover",
      "focus",
    ],
    backgroundImage: ["responsive"],
    backgroundOpacity: [
      "responsive",
      "group-hover",
      "focus-within",
      "hover",
      "focus",
    ],
    backgroundPosition: ["responsive"],
    backgroundRepeat: ["responsive"],
    backgroundSize: ["responsive"],
    borderCollapse: ["responsive"],
    borderColor: [
      "responsive",
      "dark",
      "group-hover",
      "focus-within",
      "hover",
      "focus",
    ],
    borderOpacity: [
      "responsive",
      "group-hover",
      "focus-within",
      "hover",
      "focus",
    ],
    borderRadius: ["responsive"],
    borderStyle: ["responsive"],
    borderWidth: ["responsive"],
    boxShadow: ["responsive", "group-hover", "focus-within", "hover", "focus"],
    boxSizing: ["responsive"],
    clear: ["responsive"],
    container: ["responsive"],
    cursor: ["responsive"],
    display: ["responsive"],
    divideColor: ["responsive", "dark"],
    divideOpacity: ["responsive"],
    divideStyle: ["responsive"],
    divideWidth: ["responsive"],
    fill: ["responsive"],
    flex: ["responsive"],
    flexDirection: ["responsive"],
    flexGrow: ["responsive"],
    flexShrink: ["responsive"],
    flexWrap: ["responsive"],
    float: ["responsive"],
    fontFamily: ["responsive"],
    fontSize: ["responsive"],
    fontSmoothing: ["responsive"],
    fontStyle: ["responsive"],
    fontVariantNumeric: ["responsive"],
    fontWeight: ["responsive"],
    gap: ["responsive"],
    gradientColorStops: ["responsive", "dark", "hover", "focus"],
    gridAutoColumns: ["responsive"],
    gridAutoFlow: ["responsive"],
    gridAutoRows: ["responsive"],
    gridColumn: ["responsive"],
    gridColumnEnd: ["responsive"],
    gridColumnStart: ["responsive"],
    gridRow: ["responsive"],
    gridRowEnd: ["responsive"],
    gridRowStart: ["responsive"],
    gridTemplateColumns: ["responsive"],
    gridTemplateRows: ["responsive"],
    height: ["responsive"],
    inset: ["responsive"],
    justifyContent: ["responsive"],
    justifyItems: ["responsive"],
    justifySelf: ["responsive"],
    letterSpacing: ["responsive"],
    lineHeight: ["responsive"],
    listStylePosition: ["responsive"],
    listStyleType: ["responsive"],
    margin: ["responsive"],
    maxHeight: ["responsive"],
    maxWidth: ["responsive"],
    minHeight: ["responsive"],
    minWidth: ["responsive"],
    objectFit: ["responsive"],
    objectPosition: ["responsive"],
    opacity: ["responsive", "group-hover", "focus-within", "hover", "focus"],
    order: ["responsive"],
    outline: ["responsive", "focus-within", "focus"],
    overflow: ["responsive"],
    overscrollBehavior: ["responsive"],
    padding: ["responsive"],
    placeContent: ["responsive"],
    placeItems: ["responsive"],
    placeSelf: ["responsive"],
    placeholderColor: ["responsive", "dark", "focus"],
    placeholderOpacity: ["responsive", "focus"],
    pointerEvents: ["responsive"],
    position: ["responsive"],
    resize: ["responsive"],
    ringColor: ["responsive", "dark", "focus-within", "focus"],
    ringOffsetColor: ["responsive", "dark", "focus-within", "focus"],
    ringOffsetWidth: ["responsive", "focus-within", "focus"],
    ringOpacity: ["responsive", "focus-within", "focus"],
    ringWidth: ["responsive", "focus-within", "focus"],
    rotate: ["responsive", "hover", "focus"],
    scale: ["responsive", "hover", "focus"],
    skew: ["responsive", "hover", "focus"],
    space: ["responsive"],
    stroke: ["responsive"],
    strokeWidth: ["responsive"],
    tableLayout: ["responsive"],
    textAlign: ["responsive"],
    textColor: [
      "responsive",
      "dark",
      "group-hover",
      "focus-within",
      "hover",
      "focus",
    ],
    textDecoration: [
      "responsive",
      "group-hover",
      "focus-within",
      "hover",
      "focus",
    ],
    textOpacity: [
      "responsive",
      "group-hover",
      "focus-within",
      "hover",
      "focus",
    ],
    textOverflow: ["responsive"],
    textTransform: ["responsive"],
    transform: ["responsive"],
    transformOrigin: ["responsive"],
    transitionDelay: ["responsive"],
    transitionDuration: ["responsive"],
    transitionProperty: ["responsive"],
    transitionTimingFunction: ["responsive"],
    translate: ["responsive", "hover", "focus"],
    userSelect: ["responsive"],
    verticalAlign: ["responsive"],
    visibility: ["responsive"],
    whitespace: ["responsive"],
    width: ["responsive"],
    wordBreak: ["responsive"],
    zIndex: ["responsive", "focus-within", "focus"],
  },
};
