name: CI - JS

on:
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  JS:
    runs-on: ubuntu-latest
    steps:
      - name: SETUP - Checkout code
        uses: actions/checkout@v4

      - name: SETUP - Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm

      - name: SETUP - Install dependencies
        run: npm ci --prefer-offline &> /dev/null

      - name: ANALYZE - Run TSC
        run: tsc -p tsconfig.json --noEmit

      - name: ANALYZE - Run ESLint
        run: npm run lint

  deploy-staging:
      name: Deploy to Staging
      runs-on: ubuntu-latest
      needs: lint
      # on every branch that isnt master
      if: github.ref != 'refs/heads/master'
      steps:
        - uses: actions/checkout@master
        - uses: amondnet/vercel-action@v20
          with:
            vercel-token: ${{ secrets.VERCEL_TOKEN }}
            vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
            vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
            github-token: ${{ secrets.GITHUB_TOKEN }}
            github-comment: true

    deploy-prod:
      name: Deploy to Production
      runs-on: ubuntu-latest
      needs: lint
      if: github.ref == 'refs/heads/master'
      steps:
        - uses: actions/checkout@master
        - uses: amondnet/vercel-action@v20
          with:
            vercel-token: ${{ secrets.VERCEL_TOKEN }}
            vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
            vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
            github-token: ${{ secrets.GITHUB_TOKEN }}
            github-comment: true
            vercel-args: '--prod'